hack: run tauri dev and expect failure to generate bindings

diff --git a/.github/workflows/e2e-tests.yml b/.github/workflows/e2e-tests.yml
--- a/.github/workflows/e2e-tests.yml
+++ b/.github/workflows/e2e-tests.yml
@@ -56,6 +56,13 @@ jobs:
       - name: Install tauri-driver
         run: cargo install tauri-driver --locked
 
+      # HACK: generate bindings by running tauri dev
+      # this is expected to fail since we don't have a graphical environment
+      # and we aren't running the necessary containers at this point
+      # required because TauRPC only generates bindings in tauri dev mode
+      - name: Generate Bindings
+        run: bun run tauri dev || true
+
       # pull the docker containers
       - name: Pull Docker Containers
         run: docker compose pull
@@ -73,12 +80,6 @@ jobs:
       # since the Tauri application requires it to be active
       - name: Start Map Server
         run: bun run osm:run -d
-
-      # build the Rust backend first since it generates
-      # typescript bindings as part of the build process
-      - name: Build Rust Backend
-        run: cargo build
-        working-directory: src-tauri
 
       # run the Selenium test suite on Linux.
       # we run it through `xvfb-run` (the dependency we installed earlier) to have a fake
